[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
blst = { 'git' = 'https://github.com/supranational/blst.git' }
sha2 = { version = "0.10.6", default-features = false }
num_cpus = { version = "1.16.0", optional = true }
rayon = { version = "1.8.0", optional = true } 
threadpool = "^1.8.1"

[features]
default = [
    "rand",
    "std",
]
rand = []
std = [
    "sha2/std"
]
parallel = [
    "dep:rayon",
    "dep:num_cpus"
]
