name: tests
on: [push, pull_request, workflow_dispatch]
env:
  C_KZG_4844_GIT_HASH: '624aa60d01da524827123506975431aa5454c80d'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Excluding mcl for now due to they have different project layout
        backend: [blst, arkworks]
        include:
          # Set default clippy flag to all-features
          - clippy-flag: --all-features
          # Setup exec_once_per_backend flag
          - os: ubuntu-latest
            exec_once_per_backend: true
          # Setup exec_once_overall flag
          - os: ubuntu-latest
            backend: blst
            exec_once_overall: true
          # Select backends which support wasm & which support ckzg drop-in
          - backend: blst
            support_wasm: true
            support_ckzg: true
            # Override all-features flag for blst, due to incompatibility between portable & force-adx
            clippy-flag: --features=default,std,rand,parallel
          - backend: arkworks
            support_wasm: true
            support_ckzg: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc
          pip install PyYAML
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      # Check ckzg backend tests
      - name: "${{ matrix.backend }} Tests (c-kzg-4844)"
        if: matrix.exec_once_per_backend && matrix.support_ckzg
        run: |
          bash run-c-kzg-4844-tests.sh ${{ matrix.backend }}

      # Check parallel ckzg backend tests
      - name: "${{ matrix.backend }} Tests (c-kzg-4844 parallel)"
        if: matrix.exec_once_per_backend && matrix.support_ckzg
        run: |
          bash run-c-kzg-4844-tests.sh --parallel ${{ matrix.backend }}
